In [1]:
%%HTML
<style type="text/css">
table.dataframe td, table.dataframe th {
    border: 1px  black solid !important;
  color: black !important;
}
</style>

In [22]:
import pandas as pd

In [3]:
df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='â„–':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

In [25]:
sd = df.copy()

In [26]:
sd['countries'] = sd.index

In [39]:
(sd['Gold']-sd['Gold.1']).max()

880

In [76]:
df_gold = df[(df['Gold']>0) & (df['Gold.1']>0)]
s = (abs(df_gold['Gold']-df_gold['Gold.1'])/df_gold['Gold.2'])

In [78]:
s.idxmax() #returns the index of the first occurence of maximum in the requested axis of the dataframe....default is 0/'index' for row-wise, other options are 1/'columns' for column-wise

'Bulgaria'

In [84]:
points = 3*df['Gold.2'] + 2*df['Silver.2'] + df['Bronze.2']
points

Afghanistan                           2
Algeria                              27
Argentina                           130
Armenia                              16
Australasia                          22
                                   ...
Yugoslavia                          171
Independent Olympic Participants      4
Zambia                                3
Zimbabwe                             18
Mixed team                           38
Length: 146, dtype: int64

In [85]:
cen = pd.read_csv('census.csv')
cen.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [107]:
cnty_df = cen[cen['SUMLEV'] == 50]
cnty_df.head(20)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121

In [97]:
cnty_df = cnty_df.set_index(['STNAME','CTYNAME'])

In [108]:
x = cnty_df.groupby('STNAME').count()['SUMLEV']
x.idxmax()

'Texas'

In [124]:
pop_county_df = cnty_df.sort_values(by=['STNAME','CENSUS2010POP'], ascending=False).groupby('STNAME').head(3)

In [125]:
pop_county_df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3137,50,2,3,55,79,Wisconsin,Milwaukee County,947735,947736,948301,...,-4.417899,-5.257085,-5.581617,-8.303054,-8.604921,-2.352634,-2.953702,-3.114494,-5.344614,-5.623163
3109,50,2,3,55,25,Wisconsin,Dane County,488073,488075,489187,...,5.468267,4.529574,3.392786,3.107322,2.481328,8.430668,7.729273,6.874337,7.038202,6.383028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,50,4,9,2,90,Alaska,Fairbanks North Star Borough,97581,97581,98289,...,-17.339069,5.430293,-9.147023,-33.436804,-13.859157,-15.791483,10.618791,-4.926084,-29.823633,-8.984834
85,50,4,9,2,170,Alaska,Matanuska-Susitna Borough,88995,88995,89761,...,13.050517,11.474315,12.906763,15.008086,18.697964,13.391923,12.303913,13.528903,15.605525,19.349985
37,50,3,6,1,73,Alabama,Jefferson County,658466,658350,658116,...,-4.138628,-4.492646,-1.664873,-0.970225,-3.337536,-2.985041,-3.536344,-0.647113,0.221333,-2.126089
49,50,3,6,1,97,Alabama,Mobile County,412992,413143,413332,...,-5.242052,-3.722733,-3.181655,-2.311087,-3.873201,-3.751237,-2.281051,-1.753896,-0.759909,-2.288272
45,50,3,6,1,89,Alabama,Madison County,334811,334811,336138,...,4.170416,3.438521,6.367708,4.064107,2.480087,5.739131,4.880766,7.818211,5.734524,4.180881

In [127]:
columns_to_keep = ['STNAME',
                                  'CTYNAME',
                                  'POPESTIMATE2010',
                                  'POPESTIMATE2011',
                                  'POPESTIMATE2012',
                                  'POPESTIMATE2013',
                                  'POPESTIMATE2014',
                                  'POPESTIMATE2015']

In [128]:
change_df = cnty_df[columns_to_keep]

In [139]:
change_df

,STNAME,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,54660,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,183193,186659,190396,195126,199713,203709
3,Alabama,Barbour County,27341,27226,27159,26973,26815,26489
4,Alabama,Bibb County,22861,22733,22642,22512,22549,22583
5,Alabama,Blount County,57373,57711,57776,57734,57658,57673
...,...,...,...,...,...,...,...,...
3188,Wyoming,Sweetwater County,43593,44041,45104,45162,44925,44626
3189,Wyoming,Teton County,21297,21482,21697,22347,22905,23125
3190,Wyoming,Uinta County,21102,20912,20989,21022,20903,20822
3191,Wyoming,Washakie County,8545,8469,8443,8443,8316,8328
3192,Wyoming,Weston County,7181,7114,7065,7160,7185,7234

In [144]:
cnty_df['Diff'] = abs(cnty_df['POPESTIMATE2015'] - cnty_df['POPESTIMATE2014'])+abs(cnty_df['POPESTIMATE2014'] - cnty_df['POPESTIMATE2013'])+abs(cnty_df['POPESTIMATE2013'] -
                                                                                                                                                cnty_df['POPESTIMATE2012'])+abs(cnty_df['POPESTIMATE2012'] - cnty_df['POPESTIMATE2011'])+abs(cnty_df['POPESTIMATE2011'] - cnty_df['POPESTIMATE2010'])

C:\Users\subha\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [147]:
a = max(cnty_df['Diff'])

In [149]:
ans = cnty_df['CTYNAME'][cnty_df['Diff']==a].tolist()

In [150]:
ans[0]

'Harris County'

In [151]:
ans = cnty_df[((cnty_df['REGION'] == 1) | (cnty_df['REGION']==2)) & (cnty_df['CTYNAME']=='Washington County') & 
                   (cnty_df['POPESTIMATE2015'] > cnty_df['POPESTIMATE2014'])][['STNAME','CTYNAME']]

In [156]:
    cnty_df = cen[cen['SUMLEV'] == 50]
    pop_county_df = cnty_df.sort_values(by=['STNAME','CENSUS2010POP'], ascending=False).groupby('STNAME').head(3)
    ans = pop_county_df.groupby('STNAME').sum().sort_values(by='CENSUS2010POP').head(3).index.tolist()

In [157]:
ans

['Wyoming', 'Vermont', 'North Dakota']